# Generated by Django 3.2 on 2023-04-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('money_spent', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('product_image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('money_spent', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('product_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
