# Generated by Django 3.2 on 2023-04-09 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
