# Generated by Django 3.2 on 2023-04-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_auto_20230409_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incoming',
            old_name='money_spent',
            new_name='money_received',
        ),
    ]
