# Generated by Django 3.2 on 2023-05-02 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0003_rename_money_spent_incoming_money_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='product_image',
        ),
    ]
